### ISSUE TITLE
Error at Start

### ISSUE THREAD

**Issue by AlbertFR** [componentjs/guide#27]
Hi,

I have this error :+1: 
democracyos:build Found error resolving dependencies tree TypeError: Cannot call method 'filter' of null +14s
TypeError: Cannot call method 'filter' of null

any ideas ?

I'm on ubuntu 14.04 on an x64 system

**Comment by timaschew** [comment]
Please provide commands or a script how to reproduce your problem, otherwise I cannot help you.

**Comment by AlbertFR** [comment]
I'm perhaps not in the good place sorry
but I do a make run to compile democracyos

**Comment by timaschew** [comment]
please report the issue to democracyos
